CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    email   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS item_request
(
    id           BIGINT AUTO_INCREMENT NOT NULL,
    description  VARCHAR(255),
    requestor_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created      TIMESTAMP,
    CONSTRAINT pk_itemrequest PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT AUTO_INCREMENT NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    available   BOOLEAN               NOT NULL,
    owner_id    BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    request_id  BIGINT,
    CONSTRAINT pk_items PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS booking
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start          TIMESTAMP,
    end_booking    TIMESTAMP,
    item_id        BIGINT REFERENCES items (id) ON DELETE CASCADE,
    booker_user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    status         VARCHAR(255),
    CONSTRAINT pk_booking PRIMARY KEY (id)
);

