CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    email   VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS item_request
(
    item_request_id BIGINT AUTO_INCREMENT NOT NULL,
    description     VARCHAR(255),
    requestor_id    BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created         TIMESTAMP,
    CONSTRAINT pk_itemrequest PRIMARY KEY (item_request_id)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id     BIGINT AUTO_INCREMENT NOT NULL,
    name        VARCHAR(255),
    description VARCHAR(255),
    available   BOOLEAN               NOT NULL,
    owner_id    BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    request_id  BIGINT REFERENCES item_request (item_request_id) ON DELETE CASCADE,
    CONSTRAINT pk_items PRIMARY KEY (item_id)
);


CREATE TABLE IF NOT EXISTS booking
(
    booking_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start          TIMESTAMP WITHOUT TIME ZONE,
    end_booking    TIMESTAMP WITHOUT TIME ZONE,
    item_id        BIGINT REFERENCES items (item_id) ON DELETE CASCADE,
    booker_user_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    status         VARCHAR(255),
    CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);

