CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    email   VARCHAR(255) UNIQUE,
    CONSTRAINT pk_users PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS item_requests
(
    request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description  VARCHAR(255),
    requestor_id BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    created      TIMESTAMP,
    CONSTRAINT pk_item_request PRIMARY KEY (request_id)
);

CREATE TABLE IF NOT EXISTS items
(
    item_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR(255),
    description     VARCHAR(255),
    available       BOOLEAN                                 NOT NULL,
    owner_id        BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    item_request_id BIGINT REFERENCES item_requests (request_id),
    CONSTRAINT pk_items PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS comments
(
    comment_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    commentator_id BIGINT REFERENCES users (user_id),
    text           VARCHAR(255),
    item_id        BIGINT REFERENCES items (item_id),
    create_time    TIMESTAMP,
    CONSTRAINT pk_comments PRIMARY KEY (comment_id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    booking_id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    item_id        BIGINT REFERENCES items (item_id) ON DELETE CASCADE,
    booker_id      BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    booking_status VARCHAR(15),
    booking_start  TIMESTAMP,
    booking_end    TIMESTAMP,
    CONSTRAINT pk_booking PRIMARY KEY (booking_id)
);





